In [1]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in /usr/local/lib/python3.10/dist-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ucimlrepo) (2.1.4)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.10/dist-packages (from ucimlrepo) (2024.8.30)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.0->ucimlrepo) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.0->ucimlrepo) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.0->ucimlrepo) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.16.0)

In [2]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
predict_students_dropout_and_academic_success = fetch_ucirepo(id=697)

# data (as pandas dataframes)
X = predict_students_dropout_and_academic_success.data.features
y = predict_students_dropout_and_academic_success.data.targets

# metadata
print(predict_students_dropout_and_academic_success.metadata)

# variable information
print(predict_students_dropout_and_academic_success.variables)

{'uci_id': 697, 'name': "Predict Students' Dropout and Academic Success", 'repository_url': 'https://archive.ics.uci.edu/dataset/697/predict+students+dropout+and+academic+success', 'data_url': 'https://archive.ics.uci.edu/static/public/697/data.csv', 'abstract': "A dataset created from a higher education institution (acquired from several disjoint databases) related to students enrolled in different undergraduate degrees, such as agronomy, design, education, nursing, journalism, management, social service, and technologies.\nThe dataset includes information known at the time of student enrollment (academic path, demographics, and social-economic factors) and the students' academic performance at the end of the first and second semesters. \nThe data is used to build classification models to predict students' dropout and academic sucess. The problem is formulated as a three category classification task, in which there is a strong imbalance towards one of the classes.", 'area': 'Social Science', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 4424, 'num_features': 36, 'feature_types': ['Real', 'Categorical', 'Integer'], 'demographics': ['Marital Status', 'Education Level', 'Nationality', 'Occupation', 'Gender', 'Age'], 'target_col': ['Target'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2021, 'last_updated': 'Mon Feb 26 2024', 'dataset_doi': '10.24432/C5MC89', 'creators': ['Valentim Realinho', 'Mónica Vieira Martins', 'Jorge Machado', 'Luís Baptista'], 'intro_paper': {'title': "Early prediction of student's performance in higher education: a case study", 'authors': 'Mónica V. Martins, Daniel Tolledo, Jorge Machado, Luís M. T. Baptista, and Valentim Realinho', 'published_in': 'Trends and Applications in Information Systems and Technologies', 'year': 2021, 'url': 'http://www.worldcist.org/2021/', 'doi': 'http://www.doi.org/10.1007/978-3-030-72657-7_16'}, 'additional_info': {'summary': None, 'purpose': 'The dataset was created in a project that aims to contribute to the reduction of academic dropout and failure in higher education, by using machine learning techniques to identify students at risk at an early stage of their academic path, so that strategies to support them can be put into place. \n\nThe dataset includes information known at the time of student enrollment – academic path, demographics, and social-economic factors. \n\nThe problem is formulated as a three category classification task (dropout, enrolled, and graduate) at the end of the normal duration of the course. \n', 'funded_by': 'This dataset is supported by program SATDAP - Capacitação da Administração Pública under grant POCI-05-5762-FSE-000191, Portugal.', 'instances_represent': 'Each instance is a student', 'recommended_data_splits': 'The dataset was used, in our project, with a data split of 80% for training and 20% for test.', 'sensitive_data': None, 'preprocessing_description': 'We performed a rigorous data preprocessing to handle data from anomalies, unexplainable outliers, and missing values.', 'variable_info': None, 'citation': 'If you use this dataset in experiments for a scientific publication, please kindly cite our paper: \nM.V.Martins, D. Tolledo, J. Machado, L. M.T. Baptista, V.Realinho. (2021) "Early prediction of student’s performance in higher education: a case study" Trends and Applications in Information Systems and Technologies, vol.1, in Advances in Intelligent Systems and Computing series. Springer. DOI: 10.1007/978-3-030-72657-7_16'}}
                                              name     role         type  \
0                                   Marital Status  Feature      Integer
1                                 Application mode  Feature      Integer
2                                Application order  Feature      Integer
3                                           Course  Feature      Integer
4                       Daytime/evening attendance  Feature      Integer
5                           Previous qualification  Feature      Integer
6                   Previous qualification (grade)  Feature   Continuous
7                                      Nacionality  Feature      Integer
8                           Mother's qualification  Feature      Integer
9                           Father's qualification  Feature      Integer
10                             Mother's occupation  Feature      Integer
11                             Father's occupation  Feature      Integer
12                                 Admission grade  Feature   Continuous
13                                       Displaced  Feature      Integer
14                       Educational special needs  Feature      Integer
15                                          Debtor  Feature      Integer
16                         Tuition fees up to date  Feature      Integer
17                                          Gender  Feature      Integer
18                              Scholarship holder  Feature      Integer
19                               Age at enrollment  Feature      Integer
20                                   International  Feature      Integer
21             Curricular units 1st sem (credited)  Feature      Integer
22             Curricular units 1st sem (enrolled)  Feature      Integer
23          Curricular units 1st sem (evaluations)  Feature      Integer
24             Curricular units 1st sem (approved)  Feature      Integer
25                Curricular units 1st sem (grade)  Feature      Integer
26  Curricular units 1st sem (without evaluations)  Feature      Integer
27             Curricular units 2nd sem (credited)  Feature      Integer
28             Curricular units 2nd sem (enrolled)  Feature      Integer
29          Curricular units 2nd sem (evaluations)  Feature      Integer
30             Curricular units 2nd sem (approved)  Feature      Integer
31                Curricular units 2nd sem (grade)  Feature      Integer
32  Curricular units 2nd sem (without evaluations)  Feature      Integer
33                               Unemployment rate  Feature   Continuous
34                                  Inflation rate  Feature   Continuous
35                                             GDP  Feature   Continuous
36                                          Target   Target  Categorical

        demographic                                        description units  \
0    Marital Status  1 – single 2 – married 3 – widower 4 – divorce...  None
1              None  1 - 1st phase - general contingent 2 - Ordinan...  None
2              None  Application order (between 0 - first choice; a...  None
3              None  33 - Biofuel Production Technologies 171 - Ani...  None
4              None                            1 – daytime 0 - evening  None
5   Education Level  1 - Secondary education 2 - Higher education -...  None
6              None  Grade of previous qualification (between 0 and...  None
7       Nationality  1 - Portuguese; 2 - German; 6 - Spanish; 11 - ...  None
8   Education Level  1 - Secondary Education - 12th Year of Schooli...  None
9   Education Level  1 - Secondary Education - 12th Year of Schooli...  None
10       Occupation  0 - Student 1 - Representatives of the Legisla...  None
11       Occupation  0 - Student 1 - Representatives of the Legisla...  None
12             None                Admission grade (between 0 and 200)  None
13             None                                     1 – yes 0 – no  None
14             None                                     1 – yes 0 – no  None
15             None                                     1 – yes 0 – no  None
16             None                                     1 – yes 0 – no  None
17           Gender                                1 – male 0 – female  None
18             None                                     1 – yes 0 – no  None
19              Age                       Age of studend at enrollment  None
20             None                                     1 – yes 0 – no  None
21             None  Number of curricular units credited in the 1st...  None
22             None  Number of curricular units enrolled in the 1st...  None
23             None  Number of evaluations to curricular units in t...  None
24             None  Number of curricular units approved in the 1st...  None
25             None  Grade average in the 1st semester (between 0 a...  None
26             None  Number of curricular units without evalutions ...  None
27             None  Number of curricular units credited in the 2nd...  None
28             None  Number of curricular units enrolled in the 2nd...  None
29             None  Number of evaluations to curricular units in t...  None
30             None  Number of curricular units approved in the 2nd...  None
31             None  Grade average in the 2nd semester (between 0 a...  None
32             None  Number of curricular units without evalutions ...  None
33             None                              Unemployment rate (%)  None
34             None                                 Inflation rate (%)  None
35             None                                                GDP  None
36             None  Target. The problem is formulated as a three c...  None

   missing_values
0              no
1              no
2              no
3              no
4              no
5              no
6              no
7              no
8              no
9              no
10             no
11             no
12             no
13             no
14             no
15             no
16             no
17             no
18             no
19             no
20             no
21             no
22             no
23             no
24             no
25             no
26             no
27             no
28             no
29             no
30             no
31             no
32             no
33             no
34             no
35             no
36             no

In [3]:
X

,Marital Status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0,0.000000,0,10.8,1.4,1.74
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,0,6,6,6,13.666667,0,13.9,-0.3,0.79
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,0,6,0,0,0.000000,0,10.8,1.4,1.74
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,0,6,10,5,12.400000,0,9.4,-0.8,-3.12
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,0,6,6,6,13.000000,0,13.9,-0.3,0.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4419,1,1,6,9773,1,1,125.0,1,1,1,...,0,0,6,8,5,12.666667,0,15.5,2.8,-4.06
4420,1,1,2,9773,1,1,120.0,105,1,1,...,0,0,6,6,2,11.000000,0,11.1,0.6,2.02
4421,1,1,1,9500,1,1,154.0,1,37,37,...,0,0,8,9,1,13.500000,0,13.9,-0.3,0.79
4422,1,1,1,9147,1,1,180.0,1,37,37,...,0,0,5,6,5,12.000000,0,9.4,-0.8,-3.12
4423,1,10,1,9773,1,1,152.0,22,38,37,...,0,0,6,6,6,13.000000,0,12.7,3.7,-1.70

In [4]:
y

        Target
0      Dropout
1     Graduate
2      Dropout
3     Graduate
4     Graduate
...        ...
4419  Graduate
4420   Dropout
4421   Dropout
4422  Graduate
4423  Graduate

[4424 rows x 1 columns]

In [5]:
X.describe()

,Marital Status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP
count,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,...,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000
mean,1.178571,18.669078,1.727848,8856.642631,0.890823,4.577758,132.613314,1.873192,19.561935,22.275316,...,0.137658,0.541817,6.232143,8.063291,4.435805,10.230206,0.150316,11.566139,1.228029,0.001969
std,0.605747,17.484682,1.313793,2063.566416,0.311897,10.216592,13.188332,6.914514,15.603186,15.343108,...,0.690880,1.918546,2.195951,3.947951,3.014764,5.210808,0.753774,2.663850,1.382711,2.269935
min,1.000000,1.000000,0.000000,33.000000,0.000000,1.000000,95.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.600000,-0.800000,-4.060000
25%,1.000000,1.000000,1.000000,9085.000000,1.000000,1.000000,125.000000,1.000000,2.000000,3.000000,...,0.000000,0.000000,5.000000,6.000000,2.000000,10.750000,0.000000,9.400000,0.300000,-1.700000
50%,1.000000,17.000000,1.000000,9238.000000,1.000000,1.000000,133.100000,1.000000,19.000000,19.000000,...,0.000000,0.000000,6.000000,8.000000,5.000000,12.200000,0.000000,11.100000,1.400000,0.320000
75%,1.000000,39.000000,2.000000,9556.000000,1.000000,1.000000,140.000000,1.000000,37.000000,37.000000,...,0.000000,0.000000,7.000000,10.000000,6.000000,13.333333,0.000000,13.900000,2.600000,1.790000
max,6.000000,57.000000,9.000000,9991.000000,1.000000,43.000000,190.000000,109.000000,44.000000,44.000000,...,12.000000,19.000000,23.000000,33.000000,20.000000,18.571429,12.000000,16.200000,3.700000,3.510000

In [6]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 36 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital Status                                  4424 non-null   int64
 1   Application mode                                4424 non-null   int64
 2   Application order                               4424 non-null   int64
 3   Course                                          4424 non-null   int64
 4   Daytime/evening attendance                      4424 non-null   int64
 5   Previous qualification                          4424 non-null   int64
 6   Previous qualification (grade)                  4424 non-null   float64
 7   Nacionality                                     4424 non-null   int64
 8   Mother's qualification                          4424 non-null   int64
 9   Father's qualification                          4424 non-null   int64
 10  Mother's occupation                             4424 non-null   int64
 11  Father's occupation                             4424 non-null   int64
 12  Admission grade                                 4424 non-null   float64
 13  Displaced                                       4424 non-null   int64
 14  Educational special needs                       4424 non-null   int64
 15  Debtor                                          4424 non-null   int64
 16  Tuition fees up to date                         4424 non-null   int64
 17  Gender                                          4424 non-null   int64
 18  Scholarship holder                              4424 non-null   int64
 19  Age at enrollment                               4424 non-null   int64
 20  International                                   4424 non-null   int64
 21  Curricular units 1st sem (credited)             4424 non-null   int64
 22  Curricular units 1st sem (enrolled)             4424 non-null   int64
 23  Curricular units 1st sem (evaluations)          4424 non-null   int64
 24  Curricular units 1st sem (approved)             4424 non-null   int64
 25  Curricular units 1st sem (grade)                4424 non-null   float64
 26  Curricular units 1st sem (without evaluations)  4424 non-null   int64
 27  Curricular units 2nd sem (credited)             4424 non-null   int64
 28  Curricular units 2nd sem (enrolled)             4424 non-null   int64
 29  Curricular units 2nd sem (evaluations)          4424 non-null   int64
 30  Curricular units 2nd sem (approved)             4424 non-null   int64
 31  Curricular units 2nd sem (grade)                4424 non-null   float64
 32  Curricular units 2nd sem (without evaluations)  4424 non-null   int64
 33  Unemployment rate                               4424 non-null   float64
 34  Inflation rate                                  4424 non-null   float64
 35  GDP                                             4424 non-null   float64
dtypes: float64(7), int64(29)
memory usage: 1.2 MB

# All necessary Libraries

In [7]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV

from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report

In [8]:
X[['Admission grade', 'Previous qualification (grade)', 'Curricular units 1st sem (grade)', 'Curricular units 2nd sem (grade)', 'Unemployment rate', 'Inflation rate', 'GDP']] = X[['Admission grade', 'Previous qualification (grade)', 'Curricular units 1st sem (grade)', 'Curricular units 2nd sem (grade)', 'Unemployment rate', 'Inflation rate', 'GDP']].astype(np.int64)

<ipython-input-8-2b3efeef56b2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[['Admission grade', 'Previous qualification (grade)', 'Curricular units 1st sem (grade)', 'Curricular units 2nd sem (grade)', 'Unemployment rate', 'Inflation rate', 'GDP']] = X[['Admission grade', 'Previous qualification (grade)', 'Curricular units 1st sem (grade)', 'Curricular units 2nd sem (grade)', 'Unemployment rate', 'Inflation rate', 'GDP']].astype(np.int64)

In [9]:
y = y.replace({ 'Target' : { 'Dropout' : 0, 'Graduate' : 1, 'Enrolled' : 2 } })

In [11]:
# prompt: count number of target in number

y['Target'].value_counts()

Target
1    2209
0    1421
2     794
Name: count, dtype: int64

# *Splitung dataset*

In [12]:
# Split the data into training and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 23)

In [13]:
# Assuming y is your target variable
y_train = y_train.values.ravel()

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
param_grid_logistic = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100]
}

# Training models on the Training set

# LogisticRegression

# RandomForestClassifier

In [23]:
from sklearn.ensemble import RandomForestClassifier
modelRandomForestClassifier = RandomForestClassifier()
modelRandomForestClassifier.fit(X_train, y_train)

RandomForestClassifier()

In [24]:
X_train_prediction_random_forest = modelRandomForestClassifier.predict(X_train)
trainingAccuracyOfRandomForest = accuracy_score(y_train, X_train_prediction_random_forest)

In [25]:
trainingAccuracyOfRandomForest = accuracy_score(y_train, X_train_prediction_random_forest)

In [26]:
trainingAccuracyOfRandomForest

1.0

In [27]:
X_test_prediction_random_forest = modelRandomForestClassifier.predict(X_test)
testingAccuracyOfRandomForest = accuracy_score(y_test, X_test_prediction_random_forest)

In [28]:
testingAccuracyOfRandomForest

0.7740112994350282

# Using LinearGridSearchCV to optimize RandomForestClassifier for better accuracy

In [29]:
param_grid_random_forest = {
    'n_estimators': [100, 200],              # Reduced to 2 options
    'max_depth': [4, 8, None],               # Reduced to 3 options
    'max_features': [0.6, 1],                # Reduced to 2 options
    'min_samples_split': [2, 4],             # Reduced to 2 options
    'min_samples_leaf': [1, 2]               # Reduced to 2 options
}

In [30]:

from sklearn.model_selection import GridSearchCV
grid_search_random_forest_classifier = GridSearchCV(estimator=modelRandomForestClassifier, param_grid=param_grid_random_forest, cv=5)

In [31]:
grid_search_random_forest_classifier.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [4, 8, None], 'max_features': [0.6, 1],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 4],
                         'n_estimators': [100, 200]})

In [32]:
X_train_prediction_random_forest_grid_Search = grid_search_random_forest_classifier.predict(X_train)

In [35]:
X_test_prediction_random_forest_grid_Search = grid_search_random_forest_classifier.predict(X_test)

In [36]:
testingAccuracyOfRandomForestGridSearch = accuracy_score(y_test, X_test_prediction_random_forest_grid_Search)

In [37]:
testingAccuracyOfRandomForestGridSearch

0.7615819209039548

In [38]:

# Accuracy score
accuracy = accuracy_score(y_test, X_test_prediction_random_forest_grid_Search)
print("Accuracy:", accuracy)

# F1 score
f1 = f1_score(y_test, X_test_prediction_random_forest_grid_Search, average='weighted')  # Use 'weighted' for multiclass
print("F1 Score:", f1)

Accuracy: 0.7615819209039548
F1 Score: 0.7529279446827917

In [41]:
# prompt: generte grid_rf_model.pkl  and scale.pkl and download them

import pickle

# Save the best Random Forest model
filename = 'grid_rf_model.pkl'
pickle.dump(grid_search_random_forest_classifier, open(filename, 'wb'))

# Save the scaler
filename = 'scale.pkl'
pickle.dump(sc, open(filename, 'wb'))

# Download the files
from google.colab import files
files.download('grid_rf_model.pkl')
files.download('scale.pkl')

In [43]:
# prompt: download the dataset along with y target and X 34 feature

# Combine X and y
combined_df = pd.concat([X, y], axis=1)

# Save the combined DataFrame to a CSV file
combined_df.to_csv('predict_students_dropout_and_academic_success.csv', index=False)

# Download the file
files.download('predict_students_dropout_and_academic_success.csv')

In [ ]:

with open('encoder.pkl', 'wb') as encoder_file:
    pickle.dump(encoder, encoder_file)